
version: '3.3'

services:
  cit-web:
    image: 'node:14'
    volumes:
      - ./cit-web:/code
    working_dir: /code/
    networks:
      - back-tier
  web:
    build: ./web
    image: countable/cit
    volumes:
      - ./web:/code
      - static:/static
    networks:
      - back-tier
    env_file:
      - .env
    environment:
      - AUTHORITY=https://login.microsoftonline.com/
      - SCOPE=https://analysis.windows.net/powerbi/api/.default
  db:
    image: mdillon/postgis
    env_file:
      - .env
    volumes:
      - pg-data:/var/lib/postgresql/data
      - ./db:/code
    networks:
      - back-tier

  nginx:
    image: nginx:1.18
    volumes:
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - static:/static
    networks:
      - back-tier

volumes:
  pg-data:
    driver: local
  static:
    driver: local

networks:
  back-tier:
    driver: bridge
