# this is not the entire service account as it should already exist as a default account created by the openshift team.
# we do however need to modify it
kind: Secret
apiVersion: v1
metadata:
  name: {{ .Values.app_name }}-web-config
  namespace: {{ .Values.license_plate }}-{{ .Values.namespace_env }}
  labels:
    app: {{ .Values.app_name }}-web-config
stringData:
  REACT_APP_API_BASE_URL: placeholder
  REACT_APP_KEYCLOAK_URL: placeholder
  REACT_APP_KEYCLOAK_REALM: placeholder
  REACT_APP_KEYCLOAK_CLIENT: placeholder
  REACT_APP_SNOWPLOW_COLLECTOR: placeholder
  REACT_APP_GEOCODER_API_KEY: placeholder
  REACT_APP_BC_ROUTE_PLANNER_API_KEY: placeholder
  REACT_APP_POWER_BI_GROUP_ID: placeholder
  REACT_APP_POWER_BI_REPORT_ID_PUBLIC: placeholder
  REACT_APP_POWER_BI_REPORT_ID_INTERNAL: placeholder
---
kind: Secret
apiVersion: v1
metadata:
  name: {{ .Values.app_name }}-api-config
  namespace: {{ .Values.license_plate }}-{{ .Values.namespace_env }}
  labels:
    app: {{ .Values.app_name }}-api-config
stringData:
  ENV_LEVEL: placeholder
  POSTGRES_DB: placeholder
  POSTGRES_DJANGO_USER: placeholder
  POSTGRES_DJANGO_PASSWORD: placeholder
  POSTGRES_HOST: placeholder
  DEBUG: placeholder
  KEY_CLOAK_URL: placeholder
  KEY_CLOAK_REALM: placeholder
  KEY_CLOAK_CLIENT: placeholder
  ROUTE_PLANNER_API_KEY: placeholder
  EMAIL_NOTIFICATIONS_ENABLED: placeholder
  EMAIL_AUTH_HOST: placeholder
  EMAIL_SERVICE_HOST: placeholder
  EMAIL_CLIENT_ID: placeholder
  EMAIL_CLIENT_SECRET: placeholder
  EMAIL_SENDING_ADDRESS: placeholder
  EMAIL_OPPORTUNITY_LINK_HOST: placeholder
  USER_TRACKING_TO_EMAIL: placeholder
  AUTHORITY: placeholder
  SCOPE: placeholder
  TENANT_ID: placeholder
  CLIENT_ID: placeholder
  CLIENT_SECRET: placeholder
  AZURE_BLOB_STORAGE_CONNECTION_STRING: placeholder


