# Create a service account and appropriate rules/rule bindings for our patroni implementation.
---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: {{ .Values.app_name }}-patroni
  namespace: {{ .Values.license_plate }}-{{ .Values.namespace_env }}
  labels:
    app: {{ .Values.app_name }}-patroni
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Values.app_name }}-patroni
  namespace: {{ .Values.license_plate }}-{{ .Values.namespace_env }}
  labels:
    app: {{ .Values.app_name }}-patroni
rules:
  - apiGroups:
      - ""
    resources:
      - services
    verbs:
      - create
      - get
      - list
      - patch
      - update
      - watch
      - delete
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - create
      - get
      - list
      - patch
      - update
      - watch
      - delete
  - apiGroups:
      - ""
    resources:
      - endpoints
    verbs:
      - get
      - patch
      - update
      - create
      - list
      - watch
      - delete
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - ""
    resources:
      - pods/exec
    verbs:
      - create
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - list
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Values.app_name }}-patroni
  namespace: {{ .Values.license_plate }}-{{ .Values.namespace_env }}
  labels:
    app: {{ .Values.app_name }}-patroni
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .Values.app_name }}-patroni
subjects:
  - kind: ServiceAccount
    name: {{ .Values.app_name }}-patroni
---
# THIS RBAC IS NOT IN USE BECAUSE PATRONI IS NOT BEING USED IN OPENSHIFT
# We need to allow the cit-patroni SA to access image streams in the tools namespace
#kind: RoleBinding
#apiVersion: rbac.authorization.k8s.io/v1
#metadata:
#  name: {{ .Values.app_name }}-patroni-imagepuller
#  namespace: {{ .Values.license_plate }}-tools
#  labels:
#    app: {{ .Values.app_name }}-patroni
#roleRef:
#    apiGroup: rbac.authorization.k8s.io
#    kind: ClusterRole
#    name: system:image-puller
#subjects:
#  - kind: ServiceAccount
#    name: {{ .Values.app_name }}-patroni
#    namespace: {{ .Values.license_plate }}-dev
#  - kind: ServiceAccount
#    name: {{ .Values.app_name }}-patroni
#    namespace: {{ .Values.license_plate }}-test
#  - kind: ServiceAccount
#    name: {{ .Values.app_name }}-patroni
#    namespace: {{ .Values.license_plate }}-prod
