# This workflow will build and push a new container image to Azure ACR

on:
  push:
    branches: [production]
  workflow_dispatch:

name: Deploy to Prod
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: 
      name: Production
    steps:
      # checkout the repo
      - name: "Checkout GitHub Action"
        uses: actions/checkout@master

      - name: "Build and push webapi"
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      # TODO: tags with ${{ github.sha }}
      - run: |
          docker build cit-api -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/cit-webapi:prod
          docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/cit-webapi:prod

      - name: "Build and push frontend"
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - run: |
          docker build cit3.0-web -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/cit-frontend:prod
          docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/cit-frontend:prod

      # Comment in when ready to switch app from azure to openshift in production
      #- name: "Build and push backend to Openshift" 
      #  uses: docker/login-action@v2
      #  with:
      #    registry: image-registry.apps.silver.devops.gov.bc.ca
      #    username: serviceaccount
      #    password: ${{ secrets.OCP_REGISTRY_PASSWORD }}
      #- run: |
      #    docker build cit-api -t image-registry.apps.silver.devops.gov.bc.ca/b4e935-tools/cit-webapi:prod
      #    docker push image-registry.apps.silver.devops.gov.bc.ca/b4e935-tools/cit-webapi:prod
#
      #- name: "Build and push frontend to Openshift"
      #  uses: docker/login-action@v2
      #  with:
      #    registry: image-registry.apps.silver.devops.gov.bc.ca
      #    username: serviceaccount
      #    password: ${{ secrets.OCP_REGISTRY_PASSWORD }}
      #- run: |
      #    docker build cit3.0-web -t image-registry.apps.silver.devops.gov.bc.ca/b4e935-tools/cit-frontend:prod
      #    docker push image-registry.apps.silver.devops.gov.bc.ca/b4e935-tools/cit-frontend:prod


